// AUTO-GENERATED by fresh — do not edit.
//
// Aggregate of every loaded plugin's isolated-declarations
// emit (oxc). This is what makes `editor.getPluginApi("foo")`
// return a typed result in init.ts / downstream plugins —
// each plugin that declares `FreshPluginRegistry` here
// contributes its augmentation.

// ── dashboard ─────────────────────
export type DashboardColor = "muted" | "accent" | "value" | "number" | "ok" | "warn" | "err" | "branch";
export type DashboardTextOpts = {
	color?: DashboardColor;
	bold?: boolean;
	/** OSC-8 hyperlink target; terminals that honor it render the span as a
	*  clickable link. When only `onClick` is set (no `url`), the span is
	*  still routed through Fresh's own mouse-click dispatch. */
	url?: string;
	/** Invoked when the user clicks anywhere on the row carrying this text
	*  span, regardless of whether the terminal honors OSC-8. Multiple text
	*  spans on the same row share a single row-level click target; the
	*  first `onClick` emitted wins. */
	onClick?: () => void;
};
export type DashboardContext = {
	/** Emit a label/value row like "    label     value". The label
	*  column is padded to 10 cols so multi-row sections align. */
	kv(label: string, value: string, color?: DashboardColor): void;
	/** Emit a styled text segment on the current row. No newline is
	*  added — call `newline()` when the row is finished. */
	text(s: string, opts?: DashboardTextOpts): void;
	/** End the current row. */
	newline(): void;
	/** Shortcut for a single-row error message: "    status    why". */
	error(message: string): void;
};
export type SectionRefresh = (ctx: DashboardContext) => Promise<void>;
/**
* Public surface of the bundled `dashboard` plugin, reachable through
* `editor.getPluginApi("dashboard")`. Third-party plugins and user
* init.ts can contribute their own rows via `registerSection`, and can
* tear them down again via `removeSection` / `clearAllSections`.
*/
export type DashboardApi = {
	registerSection(name: string, refresh: SectionRefresh): () => void;
	/** Remove every registered section whose name matches `name`.
	*  Returns true if at least one section was removed. */
	removeSection(name: string): boolean;
	/** Remove every registered section, including the bundled
	*  built-ins (git, disk). */
	clearAllSections(): void;
	/** Toggle the ambient auto-open behaviour for this session.
	*  Equivalent to setting `plugins.dashboard.auto-open` in the
	*  user config, but scoped to the current process. */
	setAutoOpen(enabled: boolean): void;
	/** Refresh handlers for the built-in widgets that aren't
	*  registered by default (both hit the network). Pass one to
	*  `registerSection` from init.ts to enable it. */
	builtinHandlers: {
		weather: SectionRefresh;
		github: SectionRefresh;
	};
};
declare global {
	interface FreshPluginRegistry {
		dashboard: DashboardApi;
	}
}

