[fish]
target = "~/.config/fish"
labels = [["macos", "linux"], "cli"]

[fresh]
target = "~/.config/fresh"
labels = [["macos", "linux"], "cli"]

[[ghostty]]
source = "config/ghostty/macos"
target = "~/Library/Application Support/com.mitchellh.ghostty"
labels = ["macos", "cli"]

[[ghostty]]
source = "config/ghostty/linux"
target = "~/.config/ghostty"
labels = ["linux", "cli"]

[gram]
target = "~/.config/gram"
labels = [["macos", "linux"], ["cli", "dev"]]

[[mise]]
source = "config/mise/main.toml"
target = "~/.config/mise.toml"
labels = ["cli"]

[[mise]]
source = "config/mise/config-macos.toml"
target = "~/.config/mise/conf.d/config-macos.toml"
labels = ["macos", "cli"]

[[mise]]
source = "config/mise/ai.toml"
target = "~/.config/mise/conf.d/ai.toml"
labels = ["ai"]

[[mise]]
source = "config/mise/dev.toml"
target = "~/.config/mise/conf.d/dev.toml"
labels = ["dev"]

[[mise]]
source = "config/mise/design.toml"
target = "~/.config/mise/conf.d/design.toml"
labels = ["design"]

[[mise]]
source = "config/mise/making.toml"
target = "~/.config/mise/conf.d/making.toml"
labels = ["making"]

[[mise]]
source = "config/mise/media.toml"
target = "~/.config/mise/conf.d/media.toml"
labels = ["media"]

[[mise]]
source = "config/mise/work.toml"
target = "~/.config/mise/conf.d/work.toml"
labels = ["work"]

[[mise]]
source = "config/mise/dev-apple.toml"
target = "~/.config/mise/conf.d/dev-apple.toml"
labels = ["dev-apple"]

[[claude]]
source = "config/agents/commands"
target = "~/.claude/commands"
labels = ["ai"]

[[claude]]
source = "config/agents/rules"
target = "~/.claude/rules"
labels = ["ai"]

[[claude]]
source = "config/agents/skills"
target = "~/.claude/skills"
labels = ["ai"]

[[claude]]
source = "config/agents/agents"
target = "~/.claude/agents"
labels = ["ai"]

[[codex]]
source = "config/agents/commands"
target = "~/.codex/commands"
labels = ["work"]

[[codex]]
source = "config/agents/rules"
target = "~/.codex/rules"
labels = ["work"]

[[codex]]
source = "config/agents/skills"
target = "~/.codex/skills"
labels = ["work"]

[[codex]]
source = "config/agents/agents"
target = "~/.codex/agents"
labels = ["work"]

[[herdr]]
source = "config/herdr/config.toml"
target = "~/.config/herdr/config.toml"
labels = [["macos", "linux"], "ai"]

[[starship]]
source = "config/starship/starship.toml"
target = "~/.config/starship.toml"
labels = ["cli"]

[[xccolortheme]]
source = "externals/daltonmenezes/aura-theme/packages/xcode/Aura Soft Dark.xccolortheme"
target = "~/Library/Developer/Xcode/UserData/FontAndColorThemes/Favorite.xccolortheme"
labels = ["macos", "dev-apple"]

[test]
target = "~/.test"
labels = ["test"]
