[tools]
python = "latest"
uv = "latest"

[env]
UV_CACHE_DIR = "{{env.HOME}}/.home/cache/uv-cache"
UV_TOOL_BIN_DIR = "{{env.HOME}}/.home/cache/uv-bin"
UV_TOOL_DIR = "{{env.HOME}}/.home/cache/uv-tools"
